spring:
  application:
    name: I-mean
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Python 서비스 설정
python:
  service:
    url: ${PYTHON_SERVICE_URL:http://localhost:5000}
    timeout:
      connect: 5s
      read: 30s
    retry:
      max-attempts: 3
      delay: 1s

# 로깅 설정
logging:
  level:
    com.ohgiraffers.tomatolab_imean.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
