name: CI / Spring Boot

env:
  PROFILE: test

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      PROFILE: dev  # 환경 변수 설정 (build.gradle에서 참조)

    steps:
      - uses: actions/checkout@v4  # 최신 버전 v4 사용

      - name: Set up JDK 17
        uses: actions/setup-java@v4  # 최신 버전 v4 사용
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew build --no-daemon